

global proc int glTFTranslatorOpts ( string $parent,
									string $action,
									string $initialSettings,
									string $resultCallback )
//
//	Description:
//		This script posts the LEP file translator options.
//		The optionsString is of the form:
//			varName1=value1;varName2=value2;...
//		for the LEP translator, there is only one option named "t",
//		which can have 2 value.  If it is "1" (or true), then on writing
//		Dag node type names are written, otherwise, it is "0" and type
//		names are not written.
//
//	Parameters:
//		$parent	- the elf parent layout for this options layout. It is
//					always a scrollLayout.
//		$action	- the action that is to be performed with this invokation
//					of this proc. Valid options are:
//						"query" - construct the options string and pass it
//									to the resultCallback.
//						"post"	- post all the elf controls.
//		$initialSettings - the current options string in effect at the
//						   time this script is invoked.
//		$resultCallback	-
//				This is the proc to be called with the result string. 
//				resultCallback ( string $optionsString )
//
//	Returns:
//		1 if successfull.
//		0 otherwise.
//
{
	int		$bResult;
	string	$currentOptions;
	string	$optionList[];
	string	$optionBreakDown[];
	int		$index;
	
	if ($action == "post") {
		setParent $parent;
		columnLayout -adjustableColumn true glTFOptsCol;
			optionMenu -label "Resources Format:" -annotation "Only applies to gltf format (not glb)" resFormatOpts;
				menuItem -label "Single .bin";
				menuItem -label "Copy source files";
				menuItem -label "Embedded";
			optionMenu -label "Export Animation:" animOpts;
				menuItem -label "None";
				menuItem -label "Keyed";
				menuItem -label "Frames as Scenes";
			radioButtonGrp -numberOfRadioButtons 2 -label "Materials" -labelArray2 "On" "Off" includeMaterialsOpts;
			radioButtonGrp -numberOfRadioButtons 2 -label "Normals" -labelArray2 "On" "Off" includeNormalsOpts;
			radioButtonGrp -numberOfRadioButtons 2 -label "Flip V" -labelArray2 "On" "Off" vFlipOpts;
			radioButtonGrp -numberOfRadioButtons 2 -label "Apply Transforms" -labelArray2 "On" "Off" transformsAppliedOpts;
			radioButtonGrp -numberOfRadioButtons 2 -label "Join Child Meshes" -labelArray2 "On" "Off" joinMeshesOpts;
		setParent ..;

		// Now set to current settings.
		if (size($initialSettings) > 0) {
			tokenize($initialSettings, ";", $optionList);
			for ($index = 0; $index < size($optionList); $index++) {
				tokenize($optionList[$index], "=", $optionBreakDown);
				if ($optionBreakDown[0] == "resFormat") {
					if ($optionBreakDown[1] == "bin") {
						optionMenu -edit -select 1 resFormatOpts;
					} else if ($optionBreakDown[1] == "source"){
						optionMenu -edit -select 2 resFormatOpts;
					} else {
						optionMenu -edit -select 3 resFormatOpts;
					}
				}
				else if ($optionBreakDown[0] == "anim") {
					if ($optionBreakDown[1] == "none") {
						optionMenu -edit -select 1 animOpts;
					} else if ($optionBreakDown[1] == "keyed") {
						optionMenu -edit -select 2 animOpts;
					} else if ($optionBreakDown[1] == "frames") {
						optionMenu -edit -select 3 animOpts;
					}
				}
				else if ($optionBreakDown[0] == "vFlip") {
					if ($optionBreakDown[1] == "0") {
					radioButtonGrp -edit -select 2 vFlipOpts;
					} else {
						radioButtonGrp -edit -select 1 vFlipOpts;
					}
				}
				else if ($optionBreakDown[0] == "includeMaterials") {
					if ($optionBreakDown[1] == "0") {
						radioButtonGrp -edit -select 2 includeMaterialsOpts;
					} else {
						radioButtonGrp -edit -select 1 includeMaterialsOpts;
					}
				}
				else if ($optionBreakDown[0] == "includeNormals") {
					if ($optionBreakDown[1] == "0") {
						radioButtonGrp -edit -select 2 includeNormalsOpts;
					} else {
						radioButtonGrp -edit -select 1 includeNormalsOpts;
					}
				}
				else if ($optionBreakDown[0] == "transformsApplied") {
					if ($optionBreakDown[1] == "0") {
						radioButtonGrp -edit -select 2 transformsAppliedOpts;
					} else {
						radioButtonGrp -edit -select 1 transformsAppliedOpts;
					}
				}
				else if ($optionBreakDown[0] == "joinMeshes") {
					if ($optionBreakDown[1] == "0") {
						radioButtonGrp -edit -select 2 joinMeshesOpts;
					} else {
						radioButtonGrp -edit -select 1 joinMeshesOpts;
					}
				}
			}
		}
		$result = 1;
	
	} else if ($action == "query") {
		// Set verbose option
        $currentOptions = "";
		if (`optionMenu -q -select resFormatOpts` == 1) {
			$currentOptions = $currentOptions + "resFormat=bin;";
		} else if(`optionMenu -q -select resFormatOpts` == 2) {
            $currentOptions = $currentOptions + "resFormat=source;";
        } else {
			$currentOptions = $currentOptions + "resFormat=embedded;";
		}
		if (`optionMenu -q -select animOpts` == 1) {
			$currentOptions = $currentOptions + "anim=none;";
		} else if (`optionMenu -q -select animOpts` == 2) {
			$currentOptions = $currentOptions + "anim=keyed;";
		} else
			$currentOptions = $currentOptions + "anim=frames;";
		if (`radioButtonGrp -q -select vFlipOpts` == 2) {
			$currentOptions += "vFlip=0;";
		} else {
			$currentOptions += "vFlip=1;";
		}
		if (`radioButtonGrp -q -select includeMaterialsOpts` == 2) {
			$currentOptions += "includeMaterials=0;";
		} else {
			$currentOptions += "includeMaterials=1;";
		}
		if (`radioButtonGrp -q -select includeNormalsOpts` == 2) {
			$currentOptions += "includeNormals=0;";
		} else {
			$currentOptions += "includeNormals=1;";
		}
		if (`radioButtonGrp -q -select transformsAppliedOpts` == 2) {
			$currentOptions += "transformsApplied=0;";
		} else {
			$currentOptions += "transformsApplied=1;";
		}
		if (`radioButtonGrp -q -select joinMeshesOpts` == 2) {
			$currentOptions += "joinMeshes=0;";
		} else {
			$currentOptions += "joinMeshes=1;";
		}
		eval($resultCallback+" \""+$currentOptions+"\"");
		$result = 1;
	} else {
		$bResult = 0;
	}
	
	return $bResult;
}
